kind: pipeline
name: GNU GCC 9.3 TC ARM BUILD

clone:
  disable: true

steps:
- name: GNU GCC ARM
  image: archlinux:latest
  environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      TG_BOT_API:
        from_secret: BOT_TOKEN
  commands:
    - "export GITHUB_TOKEN"
    - pacman -Sy base-devel git subversion autoconf-archive tar xz pixz lzip aria2 zip parallel zstd rsync python python3 --noconfirm
    - git clone https://github.com/Reinazhard/build-tools-gcc.git builder && cd builder
    - sed -i "s/TG_TOKEN=.*/TG_TOKEN=$TG_BOT_API/g" build
    - script -c "bash -x build -a arm -s gnu -v 9 -V -p zstd -tm" /drone/src/build-arm-gnu-gcc.log

---
kind: pipeline
name: GNU GCC 10 TC ARM BUILD

clone:
  disable: true

steps:
- name: GNU GCC ARM
  image: archlinux:latest
  environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      TG_BOT_API:
        from_secret: TG_BOT_API
  commands:
    - "export GITHUB_TOKEN"
    - pacman -Sy base-devel git subversion autoconf-archive tar xz pixz lzip aria2 zip parallel zstd rsync python python3 --noconfirm
    - git clone https://github.com/Reinazhard/build-tools-gcc.git builder && cd builder
    - sed -i "s/TG_TOKEN=.*/TG_TOKEN=$TG_BOT_API/g" build
    - script -c "bash -x build -a arm -s gnu -v 10 -V -p zstd -tm" /drone/src/build-arm-gnu-gcc.log

---
kind: pipeline
name: GNU GCC 11 TC ARM BUILD

clone:
  disable: true

steps:
- name: GNU GCC ARM
  image: archlinux:latest
  environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      TG_BOT_API:
        from_secret: TG_BOT_API
  commands:
    - "export GITHUB_TOKEN"
    - pacman -Sy base-devel git subversion autoconf-archive tar xz pixz lzip aria2 zip parallel zstd rsync python python3 --noconfirm
    - git clone https://github.com/Reinazhard/build-tools-gcc.git builder && cd builder
    - sed -i "s/TG_TOKEN=.*/TG_TOKEN=$TG_BOT_API/g" build
    - script -c "bash -x build -a arm -s gnu -v 11 -V -p zstd -tm" /drone/src/build-arm-gnu-gcc.log

---
kind: pipeline
name: GNU GCC 9.3 TC ARM64 BUILD

clone:
  disable: true

steps:
- name: GNU GCC ARM64
  image: archlinux:latest
  environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      TG_BOT_API:
        from_secret: TG_BOT_API
  commands:
    - "export GITHUB_TOKEN"
    - pacman -Sy base-devel git subversion autoconf-archive tar xz pixz lzip aria2 zip parallel zstd rsync python python3 --noconfirm
    - git clone https://github.com/Reinazhard/build-tools-gcc.git builder && cd builder
    - sed -i "s/TG_TOKEN=.*/TG_TOKEN=$TG_BOT_API/g" build
    - script -c "bash -x build -a arm64 -s gnu -v 9 -V -p zstd -tm" /drone/src/build-arm-gnu-gcc.log

---
kind: pipeline
name: GNU GCC 10 TC ARM64 BUILD

clone:
  disable: true

steps:
- name: GNU GCC ARM64
  image: archlinux:latest
  environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      TG_BOT_API:
        from_secret: TG_BOT_API
  commands:
    - "export GITHUB_TOKEN"
    - pacman -Sy base-devel git subversion autoconf-archive tar xz pixz lzip aria2 zip parallel zstd rsync python python3 --noconfirm
    - git clone https://github.com/Reinazhard/build-tools-gcc.git builder && cd builder
    - sed -i "s/TG_TOKEN=.*/TG_TOKEN=$TG_BOT_API/g" build
    - script -c "bash -x build -a arm64 -s gnu -v 10 -V -p zstd -tm" /drone/src/build-arm-gnu-gcc.log

---
kind: pipeline
name: GNU GCC 11 TC ARM64 BUILD

clone:
  disable: true

steps:
- name: GNU GCC ARM64
  image: archlinux:latest
  environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      TG_BOT_API:
        from_secret: TG_BOT_API
  commands:
    - "export GITHUB_TOKEN"
    - pacman -Sy base-devel git subversion autoconf-archive tar xz pixz lzip aria2 zip parallel zstd rsync python python3 --noconfirm
    - git clone https://github.com/Reinazhard/build-tools-gcc.git builder && cd builder
    - sed -i "s/TG_TOKEN=.*/TG_TOKEN=$TG_BOT_API/g" build
    - script -c "bash -x build -a arm64 -s gnu -v 11 -V -p zstd -tm" /drone/src/build-arm-gnu-gcc.log
